version: '3.4'

services:
  realestate.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DefaultConnection=Server=sqlserver;Database=RealEstate; User id = sa ; password = Password.123;Trusted_Connection=False"
   
    ports:
      - "80"

