version: '3.4'

services:
  realestate.api:
    image: ${DOCKER_REGISTRY-}realestateapi
    build:
      context: .
      dockerfile: RealEstate.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DefaultConnection=Server=sqlserver;Database=RealEstate; User id = sa; password = Password.123;Trusted_Connection=False"
    depends_on:
    - sqlserver
    ports:
    - "8000:80"

  sqlserver:
     image: mcr.microsoft.com/mssql/server:2022-latest
     environment:
      - SA_PASSWORD=Password.123
      - ACCEPT_EULA=Y
     ports:
      - "1433:1433" 
  


